In [74]:
import pandas as pd
import numpy as np

In [75]:
df = pd.read_csv("employee_data.csv")
df

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

### Feature engineering : when we transform our data to form new columns so that we improve the analystics and features of our data

In [76]:
# Q. make a new column as tax, if income is greater than 50k then 20% tax if not then 10%
df2 = df.copy()
df2["Gender"] = ["Female","Male","Male","Male","Female","Male","Female","Female","Male","Female"] # just makign a new column
df2["tax"] = df2["Salary"].apply(lambda x : "20%" if x >= 50000 else "10%") # 1. apply function : use another function in it like lambda
df2

   ID     Name  Age Department  Salary  Gender  tax
0   1    Alice   25         HR   55000  Female  20%
1   2      Bob   32         IT   72000    Male  20%
2   3  Charlie   28    Finance   48000    Male  10%
3   4    David   45  Marketing   91000    Male  20%
4   5      Eva   38         IT   65000  Female  20%
5   6    Frank   29    Finance   50000    Male  20%
6   7    Grace   41         HR   82000  Female  20%
7   8   Hannah   26  Marketing   47000  Female  10%
8   9      Ian   35         IT   75000    Male  20%
9  10    Julia   30    Finance   60000  Female  20%

In [77]:
# Q. make female to F and Male to M using a function

sex_map = {
    "Male" : "M",
    "Female" : "F",
    "Unknown" : "U"
}

df2["Gender"] = df2["Gender"].map(sex_map) # 2. .map is used to convert a value into another in a column
df2

   ID     Name  Age Department  Salary Gender  tax
0   1    Alice   25         HR   55000      F  20%
1   2      Bob   32         IT   72000      M  20%
2   3  Charlie   28    Finance   48000      M  10%
3   4    David   45  Marketing   91000      M  20%
4   5      Eva   38         IT   65000      F  20%
5   6    Frank   29    Finance   50000      M  20%
6   7    Grace   41         HR   82000      F  20%
7   8   Hannah   26  Marketing   47000      F  10%
8   9      Ian   35         IT   75000      M  20%
9  10    Julia   30    Finance   60000      F  20%

In [78]:
# Q. Make a new column as new salary where every employee has a promotion by 50%

df2.assign(new_salary = df2["Salary"] * 1.5) # 3. .assign makes a new column on the basis of an old column

   ID     Name  Age Department  Salary Gender  tax  new_salary
0   1    Alice   25         HR   55000      F  20%     82500.0
1   2      Bob   32         IT   72000      M  20%    108000.0
2   3  Charlie   28    Finance   48000      M  10%     72000.0
3   4    David   45  Marketing   91000      M  20%    136500.0
4   5      Eva   38         IT   65000      F  20%     97500.0
5   6    Frank   29    Finance   50000      M  20%     75000.0
6   7    Grace   41         HR   82000      F  20%    123000.0
7   8   Hannah   26  Marketing   47000      F  10%     70500.0
8   9      Ian   35         IT   75000      M  20%    112500.0
9  10    Julia   30    Finance   60000      F  20%     90000.0

In [79]:
# Q. Replace the country name "USA" to "US"
df2["Department"] = df2["Department"].replace("IT","ICT") # 4. .replace replaces all the entries to a customized new one in a column
df2

   ID     Name  Age Department  Salary Gender  tax
0   1    Alice   25         HR   55000      F  20%
1   2      Bob   32        ICT   72000      M  20%
2   3  Charlie   28    Finance   48000      M  10%
3   4    David   45  Marketing   91000      M  20%
4   5      Eva   38        ICT   65000      F  20%
5   6    Frank   29    Finance   50000      M  20%
6   7    Grace   41         HR   82000      F  20%
7   8   Hannah   26  Marketing   47000      F  10%
8   9      Ian   35        ICT   75000      M  20%
9  10    Julia   30    Finance   60000      F  20%

In [80]:
# Q. Replace the name of the column Gender to Sex and the row label 1 to 1st
df2 = df2.rename(columns={"Gender" : "Sex"}) # 5. .rename helps us change the column name of the row label
df2 = df2.rename(index={1 : "1st"})
df2

     ID     Name  Age Department  Salary Sex  tax
0     1    Alice   25         HR   55000   F  20%
1st   2      Bob   32        ICT   72000   M  20%
2     3  Charlie   28    Finance   48000   M  10%
3     4    David   45  Marketing   91000   M  20%
4     5      Eva   38        ICT   65000   F  20%
5     6    Frank   29    Finance   50000   M  20%
6     7    Grace   41         HR   82000   F  20%
7     8   Hannah   26  Marketing   47000   F  10%
8     9      Ian   35        ICT   75000   M  20%
9    10    Julia   30    Finance   60000   F  20%

In [63]:
# Q. Sort data on the basis of income and age but again sort in on the basis of index as thats most imp

df2.sort_values("Salary",ascending=False)
sorted_df = df2.sort_values(["Salary","Age"]) # 6. .sort_values sorts values in a col, can pass more parameters are lists
sorted_df.sort_index() # 7. .sort_index sorts on the basis of index values

# Q. In this same data,reset it to original while preserving the sorting and then drop the indexes

sorted_df.reset_index()
sorted_df.reset_index(drop=True)

   ID     Name  Age Department  Salary Sex  tax
0   8   Hannah   26  Marketing   47000   F  10%
1   3  Charlie   28    Finance   48000   M  10%
2   6    Frank   29    Finance   50000   M  20%
3   1    Alice   25         HR   55000   F  20%
4  10    Julia   30    Finance   60000   F  20%
5   5      Eva   38        ICT   65000   F  20%
6   2      Bob   32        ICT   72000   M  20%
7   9      Ian   35        ICT   75000   M  20%
8   7    Grace   41         HR   82000   F  20%
9   4    David   45  Marketing   91000   M  20%

In [81]:
# Q. give ranks to each employee based on income

sorted_df["ranking"] = sorted_df["Salary"].rank(ascending=False) 
sorted_df

     ID     Name  Age Department  Salary Sex  tax  ranking
7     8   Hannah   26  Marketing   47000   F  10%     10.0
2     3  Charlie   28    Finance   48000   M  10%      9.0
5     6    Frank   29    Finance   50000   M  20%      8.0
0     1    Alice   25         HR   55000   F  20%      7.0
9    10    Julia   30    Finance   60000   F  20%      6.0
4     5      Eva   38        ICT   65000   F  20%      5.0
1st   2      Bob   32        ICT   72000   M  20%      4.0
8     9      Ian   35        ICT   75000   M  20%      3.0
6     7    Grace   41         HR   82000   F  20%      2.0
3     4    David   45  Marketing   91000   M  20%      1.0

### Task : from the original data (df), Shift ID column to the end

In [82]:
# the easy method
df3 = df[["Name","Age","Department","Salary","ID"]]
df3

      Name  Age Department  Salary  ID
0    Alice   25         HR   55000   1
1      Bob   32         IT   72000   2
2  Charlie   28    Finance   48000   3
3    David   45  Marketing   91000   4
4      Eva   38         IT   65000   5
5    Frank   29    Finance   50000   6
6    Grace   41         HR   82000   7
7   Hannah   26  Marketing   47000   8
8      Ian   35         IT   75000   9
9    Julia   30    Finance   60000  10

In [90]:
# Hard method
df2 = df.copy()
new_col_order = [col for col in df2.columns if col != "ID"] + ["ID"] # list comprehension
print(new_col_order)
df2[new_col_order]

['Name', 'Age', 'Department', 'Salary', 'ID']

      Name  Age Department  Salary  ID
0    Alice   25         HR   55000   1
1      Bob   32         IT   72000   2
2  Charlie   28    Finance   48000   3
3    David   45  Marketing   91000   4
4      Eva   38         IT   65000   5
5    Frank   29    Finance   50000   6
6    Grace   41         HR   82000   7
7   Hannah   26  Marketing   47000   8
8      Ian   35         IT   75000   9
9    Julia   30    Finance   60000  10

### Task :