In [13]:
import pandas as pd
df = pd.DataFrame({
    "country" : ["USA","USA","India","India"],
    "year" : [2020,2022,2021,2020],
    "sales" : [100,120,90,110],
    "profit" : [20,25,18,22]
})

df

  country  year  sales  profit
0     USA  2020    100      20
1     USA  2022    120      25
2   India  2021     90      18
3   India  2020    110      22

### Melt = Wide to Long Format

In [14]:
melted_data = df.melt(
                id_vars=["country","year"], # these are columns we want to keep
                value_vars=["sales","profit"], # these are values we want to pivot, as in merge 
                var_name = "metrics", # this is the new column where the pivoted column names would be registered as data points
                value_name = "value" # this is the new column where all the data of the pivoted columns will be transferred into
)

melted_data

  country  year metrics  value
0     USA  2020   sales    100
1     USA  2022   sales    120
2   India  2021   sales     90
3   India  2020   sales    110
4     USA  2020  profit     20
5     USA  2022  profit     25
6   India  2021  profit     18
7   India  2020  profit     22

### Pivot = Long to Wide Format

In [17]:
pivoted_data = melted_data.pivot(
    index = ["country","year"], # The columns we want to keep, unique values
    columns = "metrics", # The extra columns we want to have
    values = "value"  # the corresponding data in the extra columns we will create
)

pivoted_data

metrics       profit  sales
country year
India   2020      22    110
        2021      18     90
USA     2020      20    100
        2022      25    120