In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv("raw_data.csv")

## Handling missing values

In [13]:
# there are multiple ways to handle missing values

df.isnull() # 1. gives true wherever there is a missing value 
df.isnull().sum() # 2. we can chain the .sum() to know how many missing values in each column
df.dropna() # 3. drops all the rows which contain a null value
df.dropna(axis=1) # 4. drops all the cols which contain a null value
df.fillna(0) # 5. fills all the missing values with a value of our choosing, in this case its 0
df.ffill() # 6. fills the previous row data if there is a missing value (top to bottom)
df.bfill() # 7. fills the next row data if there is a missing value (bottom to top)

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  34.0  Canada   Female  62000.0
3    3          Alex  34.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  51000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6    Ahmed Khan  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     USA     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  31.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [5]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

## Handling duplicates

In [19]:
df.duplicated() # 1. tells via true/false which row is duplicated
df["country"].duplicated() # we can check that for a particular column or combos of columns as well
df.drop_duplicates() # 2. drops the duplicated rows/ any particular selected cols or combos of cols

# to implement drop_duplicate or any imp function to the original data, use inplace=True in the brackets, still NOT advices

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [14]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

## Handling Data Types

In [20]:
df.dtypes # 1. shows all the datatypes
df["id"] = df["id"].astype("float") # 2. change datatype to any
df

      id          name   age country   gender   income
0    1.0      John Doe  29.0     USA     Male  55000.0
1    1.0      John Doe  29.0     USA     Male  55000.0
2    2.0    Jane Smith   NaN  Canada   Female  62000.0
3    3.0          Alex   NaN     USA  Unknown  47000.0
4    4.0  Maria Garcia  34.0   Spain   Female      NaN
5    5.0        Li Wei  27.0   China     Male  51000.0
6    6.0           NaN  45.0   India   Female  73000.0
7    7.0    Ahmed Khan  38.0     NaN     Male  68000.0
8    8.0    Rachel Lee  29.0     USA   Female  62000.0
9    9.0   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10.0   Emily Davis  31.0     USA      NaN  58000.0

## Cleaning Strings

In [28]:
df["gender"].str.upper() # 1. covert to upper case
df["gender"].str.lower() # 2. covert to lower case
df["gender"].str.capitalize() # 3. covert to 1st alphabet capital and then lower case
df["name"].str.split(" ")
df["name"].str.contains("Doe",case=False)

0      True
1      True
2     False
3     False
4     False
5     False
6       NaN
7     False
8     False
9     False
10    False
Name: name, dtype: object